// <auto-generated />
using System;
using InteriorCenterBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InteriorCenterBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120191049_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InteriorCenterBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("InteriorCenterBackend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrl = "КухняМодель1.jpg",
                            Name = "Кухня Модель 1",
                            Price = 15000m,
                            Stock = 5,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrl = "КухняМодель2.jpg",
                            Name = "Кухня Модель 2",
                            Price = 18000m,
                            Stock = 3,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrl = "Модульнаякухня.jpg",
                            Name = "Модульная кухня",
                            Price = 22000m,
                            Stock = 2,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrl = "КухняCOстровом.jpg",
                            Name = "Кухня с островом",
                            Price = 32000m,
                            Stock = 8,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrl = "СпальняМодель1.jpg",
                            Name = "Спальня Модель 1",
                            Price = 25000m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrl = "Модульнаяспальн.jpg",
                            Name = "Модульная спальня",
                            Price = 30000m,
                            Stock = 9,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrl = "КроватьОртопедическая.jpg",
                            Name = "Кровать ортопедическая",
                            Price = 12000m,
                            Stock = 4,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrl = "Спальнясбалдахином.jpg",
                            Name = "Спальня с балдахином",
                            Price = 35000m,
                            Stock = 12,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Кровать, письменный стол, шкаф, полки. Материал: ЛДСП. Цвет: Белый/Голубой.",
                            ImageUrl = "МолодежнаяМодель1.jpg",
                            Name = "Молодежная Модель 1",
                            Price = 18000m,
                            Stock = 6,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Гибкая система мебели, адаптируемая под рост. Материал: ЛДСП. Цвета: на выбор.",
                            ImageUrl = "Модульнаямолодежная.jpg",
                            Name = "Модульная молодежная",
                            Price = 24000m,
                            Stock = 20,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Кровать, стол, шкаф, полки. Материал: ЛДСП. Цвет: Крафт-серый.",
                            ImageUrl = "Ронда.jpg",
                            Name = "Ронда",
                            Price = 22000m,
                            Stock = 7,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Кровать, стол с полками, шкаф. Материал: ЛДСП. Цвет: Белый/Серый.",
                            ImageUrl = "Молодежнаясрабочейзоной.jpg",
                            Name = "Молодежная с рабочей зоной",
                            Price = 20000m,
                            Stock = 5,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "4 ящика. Шкаф с полками Материал: ЛДСП. Цвет: Белый. Размеры: 80х40х90 см.",
                            ImageUrl = "Комод.jpg",
                            Name = "Комод",
                            Price = 8000m,
                            Stock = 8,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Открытая конструкция. Материал: ЛДСП. Цвет: Бук. Размеры: 100х30х180 см.",
                            ImageUrl = "Стеллаж.jpg",
                            Name = "Стеллаж",
                            Price = 5000m,
                            Stock = 15,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "3 двери. Материал: ЛДСП. Цвет: Белый/Зеркало. Размеры: 200х60х220 см.",
                            ImageUrl = "Шкафкупе.jpg",
                            Name = "Шкаф купе",
                            Price = 15000m,
                            Stock = 3,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Обеденный. Материал: ЛДСП. Цвет столешницы: Белый. Размеры: 120х80 см.",
                            ImageUrl = "Стол.jpg",
                            Name = "Стол",
                            Price = 7000m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "С мягким сиденьем. Материал: деревянный каркас, ткань. Цвет: серый.",
                            ImageUrl = "Стул.jpg",
                            Name = "Стул",
                            Price = 2500m,
                            Stock = 12,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Письменный стол c полкой. Материал: ЛДСП. Цвет: Белый. Размеры: 100х60х75 см.",
                            ImageUrl = "Письменныйстол.jpg",
                            Name = "Письменный стол",
                            Price = 6500m,
                            Stock = 9,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Диван, 2 кресла, журнальный столик. Материал: ткань, ЛДСП. Цвет: бежевый.",
                            ImageUrl = "ГостинаяМодель1.jpg",
                            Name = "Гостиная Модель 1",
                            Price = 45000m,
                            Stock = 2,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Угловой диван, столик, ТВ-тумба. Материал: ткань, ЛДСП. Цвет: серый.",
                            ImageUrl = "Гостинаямодель2.jpg",
                            Name = "Гостиная модель 2",
                            Price = 52000m,
                            Stock = 1,
                            UpdatedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("InteriorCenterBackend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("InteriorCenterBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("InteriorCenterBackend.Models.Order", b =>
                {
                    b.HasOne("InteriorCenterBackend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteriorCenterBackend.Models.Review", b =>
                {
                    b.HasOne("InteriorCenterBackend.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteriorCenterBackend.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("InteriorCenterBackend.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteriorCenterBackend.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InteriorCenterBackend.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("InteriorCenterBackend.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("InteriorCenterBackend.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
